library(tidyverse)

dailyActivity <- read_csv("data/dailyActivity_merged.csv")
dailyCalories <- read_csv("data/dailyCalories_merged.csv")
dailyIntensities <- read_csv("data/dailyIntensities_merged.csv")
dailySteps <- read_csv("data/dailySteps_merged.csv")
heartrate_seconds <- read_csv("data/heartrate_seconds_merged.csv")
hourlyCalories <- read_csv("data/hourlyCalories_merged.csv")
hourlyIntensities <- read_csv("data/hourlyIntensities_merged.csv")
hourlySteps <- read_csv("data/hourlySteps_merged.csv")
minuteCaloriesNarrow <- read_csv("data/minuteCaloriesNarrow_merged.csv")
minuteCaloriesWide <- read_csv("data/minuteCaloriesWide_merged.csv")
minuteIntensitiesNarrow <- read_csv("data/minuteIntensitiesNarrow_merged.csv")
minuteIntensitiesWide <- read_csv("data/minuteIntensitiesWide_merged.csv")
minuteMETsNarrow <- read_csv("data/minuteMETsNarrow_merged.csv")
minuteSleep <- read_csv("data/minuteSleep_merged.csv")
minuteStepsNarrow <- read_csv("data/minuteStepsNarrow_merged.csv")
minuteStepsWide <- read_csv("data/minuteStepsWide_merged.csv")
sleepDay <- read_csv("data/sleepDay_merged.csv")
weightLogInfo <- read_csv("data/weightLogInfo_merged.csv")

